name: Publish npm packages
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Must match your username"
        required: true
        type: choice
        options:
          - notaphplover

jobs:
  publish:
    name: Publish npm packages
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Validate environment matches actor
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Environment: ${{ inputs.environment }}"

          if [ "${{ inputs.environment }}" != "${{ github.actor }}" ]; then
            echo "::error::Environment must match your username"
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup

      - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: create_token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Publish npm packages
        uses: changesets/action@6d3568c53fbe1db6c1f9ab1c7fbf9092bc18627f # v1.5.3
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
